### ISSUE TITLE
Undefined index: migrations_paths

### ISSUE THREAD

**Issue by loevgaard** [Sylius/RefundPlugin#239]
I got this error: `Notice: Undefined index: migrations_paths` in a plugin because my `doctrine_migrations.yaml` config file looked like this:

```yaml
doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
```
i.e. without the

```yaml
migrations_paths:
    'App\Migrations': '%kernel.project_dir%/src/Migrations/'
```

that you have in your plugin. The error comes from this line: https://github.com/Sylius/RefundPlugin/blob/master/src/DependencyInjection/SyliusRefundExtension.php#L39
